server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
          - Path=/api/customer/**
      - id: SUPPLIER-SERVICE
        uri: lb://SUPPLIER-SERVICE
        predicates:
          - Path=/api/supplier/**
      - id: SECURITY-SERVICE
        uri: lb://SECURITY-SERVICE
        predicates:
          - Path=/api/secure/**

management:
  endpoints:
    web:
      exposure:
        include: "*"           
  endpoint:
    health:
      show-details: always